export const REPO_SEARCH = "REPO_SEARCH";
export const REPO_SEARCH_SUCCESS = "REPO_SEARCH_SUCCESS";
export const REPO_SEARCH_FAILURE = "REPO_SEARCH_FAILURE";
export const REPO_SELECT = "REPO_SELECT";
